import streamlit as st
from pkg.load_data import connect_to_county
from pkg.plotting import liquor_type_plot

st.set_page_config(page_title="Liquor Types", page_icon="🧉")
st.header('🧉 Explanatory Data Analysis: Liquor Types',divider=True)
st.markdown('''
            We explore how different liquor types contribute to gross profit across Iowa. 
            Using state- and county-level sales data, we visualize the total gross profit 
            generated by each liquor type and examine regional preferences. This analysis 
            helps identify which products are most profitable and how consumption patterns 
            vary by location.
            ''')

table='solid-dominion-452916-p4.aml_fl_tn.county'
df = connect_to_county(table)
df_liquor = df.groupby(['liquor_type'])['gross_profit'].sum().reset_index()
df_county = df.groupby(['county', 'liquor_type'])['gross_profit'].sum().reset_index()

tab1, tab2 = st.tabs(["State-Level", " County-Level"])

#############################################################

with tab1:
    st.markdown("""
                - At the state level, American Vodkas generate the highest gross profit, 
                followed by Canadian Whiskies and Straight Bourbon Whiskies.
                - Liquor types with broader market appeal, such as Vodkas and Whiskies, 
                dominate the top rankings across the state.
                """)
    
    st.subheader("Aggregate Yearly Gross Profit in Iowa vs Liquor Type")
    liquor_type_plot(df_liquor,
                     x="liquor_type",
                     y="gross_profit",
                     x_title="Liquor type",
                     y_title="Aggregate yearly gross profit")
    
with tab2:
    st.markdown("""
                - In Polk County, American Vodkas remain the top grossing liquor type, but 
                100% Agave Tequilas and Straight Bourbon Whiskies also perform strongly.
                - In Scott and Linn Counties, similar trends appear, though regional 
                preferences may influence the ranking of specific products.
                - The variation across counties highlights the importance of tailoring 
                inventory to local demand in order to maximize profit.
                """)

    st.subheader("Aggregate Yearly Gross Profit by County vs Liquor Type")
    liquor_type_plot(df_county,
                     x="liquor_type",
                     y="gross_profit",
                     color="county",
                     x_title="Liquor type",
                     y_title="Aggregate yearly gross profit")
